FROM mcr.microsoft.com/devcontainers/base:noble

RUN sudo apt update -y
RUN sudo apt install -y libwebkit2gtk-4.1-dev \
  build-essential \
  curl \
  wget \
  file \
  libxdo-dev \
  libssl-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev
